/**
 * Master key resolution.
 *
 * The key that seals bot tokens has to exist before the first token is stored,
 * but a business owner following a one click deploy cannot produce 32 random
 * bytes by hand. So the key comes from one of two places:
 *
 *   1. The MASTER_KEY secret, when the command line tool generated one during
 *      provisioning.
 *   2. KV, generated by the Worker the first time it is needed.
 *
 * The secret wins when both are present, because a secret is opaque in the
 * dashboard while a KV value is readable by anyone with account access. The KV
 * path is a deliberate trade for the deploy button flow: it still means a
 * database export on its own yields no usable credential, which is the property
 * that matters here.
 */

import { MuxelError } from "@muxel/core";

import { generateMasterKey } from "./crypto.js";
import type { Env } from "./env.js";

const KEY_NAME = "system:master_key";

/** Cached per isolate so the common path costs nothing after the first read. */
let cached: string | null = null;

/**
 * Returns the master key, generating and storing one when this deployment does
 * not have a key yet.
 */
export async function resolveMasterKey(env: Env): Promise<string> {
  if (cached !== null) {
    return cached;
  }

  if (typeof env.MASTER_KEY === "string" && env.MASTER_KEY.length > 0) {
    cached = env.MASTER_KEY;
    return cached;
  }

  const stored = await env.STATE.get(KEY_NAME);
  if (stored !== null && stored.length > 0) {
    cached = stored;
    return cached;
  }

  const generated = generateMasterKey();
  await env.STATE.put(KEY_NAME, generated);

  // Read back before committing to the value. Two cold isolates can reach this
  // point together, and sealing tokens under a key that later loses the race
  // would make them permanently unreadable.
  const confirmed = await env.STATE.get(KEY_NAME);
  cached = confirmed ?? generated;
  return cached;
}

/**
 * Returns the master key only if one already exists.
 *
 * Used on paths that must not create state, such as reporting health.
 */
export async function peekMasterKey(env: Env): Promise<string | null> {
  if (cached !== null) {
    return cached;
  }
  if (typeof env.MASTER_KEY === "string" && env.MASTER_KEY.length > 0) {
    return env.MASTER_KEY;
  }
  return env.STATE.get(KEY_NAME);
}

/** Throws when the deployment has no master key yet. */
export async function requireMasterKey(env: Env): Promise<string> {
  const key = await peekMasterKey(env);
  if (key === null) {
    throw new MuxelError("not_configured", "this deployment has not been set up yet");
  }
  return key;
}
